package com.nosiphus.yogmod.init;

import java.util.ArrayList;
import java.util.List;

import com.nosiphus.yogmod.blocks.base.*;
import com.nosiphus.yogmod.blocks.bulb.*;
import com.nosiphus.yogmod.blocks.door.*;
import com.nosiphus.yogmod.blocks.fence.*;
import com.nosiphus.yogmod.blocks.rotational.*;
import com.nosiphus.yogmod.blocks.slabs.*;
import com.nosiphus.yogmod.blocks.special.*;
import com.nosiphus.yogmod.blocks.stairs.*;
import com.nosiphus.yogmod.blocks.storage.*;
import net.minecraft.block.Block;
import net.minecraft.block.BlockFence;
import net.minecraft.block.BlockGlass;
import net.minecraft.block.BlockLadder;
import net.minecraft.block.BlockLever;
import net.minecraft.block.BlockNote;
import net.minecraft.block.BlockPane;
import net.minecraft.block.BlockSlab;
import net.minecraft.block.BlockStairs;
import net.minecraft.block.BlockTorch;
import net.minecraft.block.BlockTrapDoor;
import net.minecraft.block.material.Material;

public class ModBlocks {

	public static final List<Block> BLOCKS = new ArrayList<Block>();
	
	public static final Block AIR_VENT = new MetalBase("air_vent");
	public static final Block ASPHALT = new StoneBase("asphalt");
	public static final BlockSlab ASPHALT_DOUBLE_SLAB = new StoneSlabDouble("asphalt_double_slab", Material.ROCK, ModBlocks.ASPHALT_DOUBLE_SLAB);
	public static final BlockFence ASPHALT_FENCE = new StoneFence("asphalt_fence");
	public static final BlockSlab ASPHALT_SLAB = new StoneSlabHalf("asphalt_slab", Material.ROCK, ModBlocks.ASPHALT_SLAB, ModBlocks.ASPHALT_DOUBLE_SLAB);
	public static final BlockStairs ASPHALT_STAIRS = new StoneStairs(ASPHALT.getDefaultState(), "asphalt_stairs");
	public static final Block BEIGE_PLASTIC = new ClothBase("beige_plastic");
	public static final Block BLACK_MARBLE = new ClothBase("black_marble");
	public static final Block BLUE_PLASTIC = new ClothBase("blue_plastic");
	public static final Block BLUE_PANELING = new MetalBase("blue_paneling");
	public static final Block BRICK = new StoneBase("brick");
	public static final BlockSlab BRICK_DOUBLE_SLAB = new StoneSlabDouble("brick_double_slab", Material.ROCK, ModBlocks.BRICK_DOUBLE_SLAB);
	public static final BlockFence BRICK_FENCE = new StoneFence("brick_fence");
	public static final BlockSlab BRICK_SLAB = new StoneSlabHalf("brick_slab", Material.ROCK, ModBlocks.BRICK_SLAB, ModBlocks.BRICK_DOUBLE_SLAB);
	public static final BlockStairs BRICK_STAIRS = new StoneStairs(BRICK.getDefaultState(), "brick_stairs");
	public static final Block CAUTION_TAPE = new CautionTapeSpecial("caution_tape");
	public static final Block CIRCUITRY = new MetalBase("circuitry");
	public static final Block CLAY_TILE = new ClothBase("clay_tile");
	public static final Block CONCRETE = new StoneBase("concrete");
	public static final BlockNote CONSOLE = new ConsoleSpecial("console");
	public static final Block CORRUGATED_COPPER = new MetalBase("corrugated_copper");
	public static final Block CORRUGATED_STEEL = new MetalBase("corrugated_steel");
	public static final Block COUNTERTOP = new WoodBase("countertop");
	public static final Block CRATE = new CrateStorage("crate", Material.WOOD);
	public static final BlockLadder CURTAINS = new CurtainsSpecial("curtains");
	public static final Block CYAN_PLASTIC = new ClothBase("cyan_plastic");
	public static final Block DARK_STONE_BRICKS = new StoneBase("dark_stone_bricks");
	public static final Block DECORATIVE_CONCRETE = new MetalBase("decorative_concrete");
	public static final BlockSlab DOUBLE_STEP = new StoneSlabDouble("double_step", Material.ROCK, ModBlocks.DOUBLE_STEP);
	public static final Block FANCY_TABLE = new FancyTableSpecial("fancy_table");
	public static final Block FLUORESCENT_PANEL = new LightingBase("fluorescent_panel");
	public static final BlockGlass GLASS = new GlassSpecial("glass");
	public static final BlockPane GLASS_PANE = new GlassPaneSpecial("glass_pane");
	public static final Block GOLD_FILGAREE = new ClothBase("gold_filgaree");
	public static final Block GREEN_PLASTIC = new ClothBase("green_plastic");
	public static final Block GREEN_TILES = new StoneBase("green_tiles");
	public static final BlockSlab HALF_STEP = new StoneSlabHalf("half_step", Material.ROCK, ModBlocks.HALF_STEP, ModBlocks.DOUBLE_STEP);
	public static final BlockTrapDoor HATCH = new HatchSpecial("hatch");
	public static final Block IRON_DOOR = new IronDoor("iron_door");
	public static final Block IRON_PLATE = new MetalBase("iron_plate");
	public static final Block IRON_STACK = new MetalBase("iron_stack");
	public static final BlockLadder LADDER = new LadderSpecial("ladder");
	public static final Block LAMP = new LampBase("lamp", false);
	public static final Block LAMP_ON = new LampBase("lamp_on", true);
	public static final BlockTorch LANTERN = new LanternBulb("lantern");
	public static final BlockTorch LED = new LEDBulb(false, "led");
	public static final BlockTorch LED_ON = new LEDBulb(true, "led_on");
	public static final BlockLever LEVER = new LeverSpecial("lever");
	public static final BlockLever LEVER_CLASSIC = new LeverSpecial("lever_classic");
	public static final Block LIMESTONE_BRICK = new StoneBase("limestone_brick");
	public static final Block LINOLEUM_TILE = new StoneBase("linoleum_tile");
	public static final Block LIT_MONITOR = new LitMonitorRotational("lit_monitor");
	public static final Block MONITOR = new MonitorRotational("monitor");
	public static final Block ORANGE_PLASTIC = new ClothBase("orange_plastic");
	public static final Block PILLAR = new StoneBase("pillar");
	public static final Block PINK_STUCCO = new ClothBase("pink_stucco");
	public static final Block PIPE = new PipeRotational("pipe");
	public static final Block PLANKS_ACACIA = new WoodBase("planks_acacia");
	public static final Block PLANKS_BIG_OAK = new WoodBase("planks_big_oak");
	public static final Block PLANKS_BIRCH = new WoodBase("planks_birch");
	public static final Block PLANKS_JUNGLE = new WoodBase("planks_jungle");
	public static final Block PLANKS_OAK = new WoodBase("planks_oak");
	public static final Block PLANKS_SPRUCE = new WoodBase("planks_spruce");
	public static final BlockSlab PLANKS_ACACIA_DOUBLE_SLAB = new WoodSlabDouble("planks_acacia_double_slab", Material.WOOD, ModBlocks.PLANKS_ACACIA_DOUBLE_SLAB);
	public static final BlockSlab PLANKS_BIG_OAK_DOUBLE_SLAB = new WoodSlabDouble("planks_big_oak_double_slab", Material.WOOD, ModBlocks.PLANKS_BIG_OAK_DOUBLE_SLAB);
	public static final BlockSlab PLANKS_BIRCH_DOUBLE_SLAB = new WoodSlabDouble("planks_birch_double_slab", Material.WOOD, ModBlocks.PLANKS_BIRCH_DOUBLE_SLAB);
	public static final BlockSlab PLANKS_JUNGLE_DOUBLE_SLAB = new WoodSlabDouble("planks_jungle_double_slab", Material.WOOD, ModBlocks.PLANKS_JUNGLE_DOUBLE_SLAB);
	public static final BlockSlab PLANKS_OAK_DOUBLE_SLAB = new WoodSlabDouble("planks_oak_double_slab", Material.WOOD, ModBlocks.PLANKS_OAK_DOUBLE_SLAB);
	public static final BlockSlab PLANKS_SPRUCE_DOUBLE_SLAB = new WoodSlabDouble("planks_spruce_double_slab", Material.WOOD, ModBlocks.PLANKS_SPRUCE_DOUBLE_SLAB);
	public static final BlockFence PLANKS_ACACIA_FENCE = new WoodFence("planks_acacia_fence");
	public static final BlockFence PLANKS_BIG_OAK_FENCE = new WoodFence("planks_big_oak_fence");
	public static final BlockFence PLANKS_BIRCH_FENCE = new WoodFence("planks_birch_fence");
	public static final BlockFence PLANKS_JUNGLE_FENCE = new WoodFence("planks_jungle_fence");
	public static final BlockFence PLANKS_OAK_FENCE = new WoodFence("planks_oak_fence");
	public static final BlockFence PLANKS_SPRUCE_FENCE = new WoodFence("planks_spruce_fence");
	public static final BlockSlab PLANKS_ACACIA_SLAB = new WoodSlabHalf("planks_acacia_slab", Material.WOOD, ModBlocks.PLANKS_ACACIA_SLAB, ModBlocks.PLANKS_ACACIA_DOUBLE_SLAB);
	public static final BlockSlab PLANKS_BIG_OAK_SLAB = new WoodSlabHalf("planks_big_oak_slab", Material.WOOD, ModBlocks.PLANKS_BIG_OAK_SLAB, ModBlocks.PLANKS_BIG_OAK_DOUBLE_SLAB);
	public static final BlockSlab PLANKS_BIRCH_SLAB = new WoodSlabHalf("planks_birch_slab", Material.WOOD, ModBlocks.PLANKS_BIRCH_SLAB, ModBlocks.PLANKS_BIRCH_DOUBLE_SLAB);
	public static final BlockSlab PLANKS_JUNGLE_SLAB = new WoodSlabHalf("planks_jungle_slab", Material.WOOD, ModBlocks.PLANKS_JUNGLE_SLAB, ModBlocks.PLANKS_JUNGLE_DOUBLE_SLAB);
	public static final BlockSlab PLANKS_OAK_SLAB = new WoodSlabHalf("planks_oak_slab", Material.WOOD, ModBlocks.PLANKS_OAK_SLAB, ModBlocks.PLANKS_OAK_DOUBLE_SLAB);
	public static final BlockSlab PLANKS_SPRUCE_SLAB = new WoodSlabHalf("planks_spruce_slab", Material.WOOD, ModBlocks.PLANKS_SPRUCE_SLAB, ModBlocks.PLANKS_SPRUCE_DOUBLE_SLAB);
	public static final BlockStairs PLANKS_ACACIA_STAIRS = new WoodStairs(PLANKS_ACACIA.getDefaultState(), "planks_acacia_stairs");
	public static final BlockStairs PLANKS_BIG_OAK_STAIRS = new WoodStairs(PLANKS_BIG_OAK.getDefaultState(), "planks_big_oak_stairs");
	public static final BlockStairs PLANKS_BIRCH_STAIRS = new WoodStairs(PLANKS_BIRCH.getDefaultState(), "planks_birch_stairs");
	public static final BlockStairs PLANKS_JUNGLE_STAIRS = new WoodStairs(PLANKS_JUNGLE.getDefaultState(), "planks_jungle_stairs");
	public static final BlockStairs PLANKS_OAK_STAIRS = new WoodStairs(PLANKS_OAK.getDefaultState(), "planks_oak_stairs");
	public static final BlockStairs PLANKS_SPRUCE_STAIRS = new WoodStairs(PLANKS_SPRUCE.getDefaultState(), "planks_spruce_stairs");
	public static final Block RAW_WOOD = new WoodBase("raw_wood");
	public static final Block RED_PLASTIC = new ClothBase("red_plastic");
	public static final Block REINFORCED_PANELING = new MetalBase("reinforced_paneling");
	public static final Block RIVETED_STEEL = new MetalBase("riveted_steel");
	public static final Block RUG = new ClothBase("rug");
	public static final Block RUSTY_IRON = new MetalBase("rusty_iron");
	public static final Block SHALE = new ClothBase("shale");
	public static final Block SINK = new SinkBase("sink", Material.IRON);
	public static final Block SMOOTH_METAL = new MetalBase("smooth_metal");
	public static final BlockFence SMOOTH_METAL_FENCE = new MetalFence("smooth_metal_fence");
	public static final BlockSlab SMOOTH_METAL_DOUBLE_SLAB = new MetalSlabDouble("smooth_metal_double_slab", Material.IRON, ModBlocks.SMOOTH_METAL_DOUBLE_SLAB);
	public static final BlockStairs SMOOTH_METAL_STAIRS = new MetalStairs(SMOOTH_METAL.getDefaultState(), "smooth_metal_stairs");
	public static final BlockSlab SMOOTH_METAL_SLAB = new MetalSlabHalf("smooth_metal_slab", Material.IRON, ModBlocks.SMOOTH_METAL_SLAB, ModBlocks.SMOOTH_METAL_DOUBLE_SLAB);
	public static final Block STORAGE_CRATE = new WoodBase("storage_crate");
	public static final Block STRIPE = new StripeRotational("stripe");
	public static final Block STRIPE_INTERSECTION = new ClothBase("stripe_intersection");
	public static final Block TABLE = new TableSpecial("table");
	public static final Block TECH_ACCENT = new WoodBase("tech_accent");
	public static final Block TILE_MOSAIC = new StoneBase("tile_mosaic");
	public static final Block VIOLET_VELVET = new ClothBase("violet_velvet");
	public static final Block WOODEN_DOOR = new WoodDoor("wooden_door");
	public static final Block WHITE_LIGHTING = new LightingBase("white_lighting");
	public static final Block WHITE_MARBLE = new StoneBase("white_marble");
	public static final Block WHITE_PLASTIC = new ClothBase("white_plastic");
	
}
