# Important Notes:
# fabric.mod.json's modid field cannot be expanded, you must change it manually.
# Every field you add must be added to buildSrc/src/main/groovy/multiloader-common.gradle expandProps map.

# Project
version=2026.09.05
group=com.nosiphus.yogmod
java_version=17

# Common
minecraft_version=1.20.1
mod_name=YogMod
mod_author=Nosiphus
mod_id=yogmod
license=GPLv3
credits=Nosiphus, TheVoxelBox, Teutron, cineminecraft
description=A mod that adds the VoxelBox Scientific as separate blocks.
minecraft_version_range=[1.20.1, 1.22)
# The version of ParchmentMC that is used, see https://parchmentmc.org/docs/getting-started#choose-a-version for new versions
parchment_minecraft=1.20.1
parchment_version=2023.09.03

# Fabric
fabric_version=0.92.3+1.20.1
fabric_loader_version=0.16.9

# Forge
forge_version=47.3.10
forge_loader_version_range=[47,)

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

#JEI
jei_version=15.20.0.123

#WTHIT
wthit_version=8.21.1
badpackets_version=0.4.3
