modLoader="javafml"
loaderVersion="[40,)"
license="https://opensource.org/licenses/MIT"
issueTrackerURL="https://github.com/Nosiphus/yogmod/issues"
[[mods]]
modId="yogmod"
version="2022.07.02"
displayName="YogMod"
updateJSONURL="https://www.nosiphus.com/"
displayURL="https://www.nosiphus.com/"
logoFile="yogmod.png"
credits="TheVoxelBox"
authors="Nosiphus"
description="A mod that adds the VoxelBox Scientific as separate blocks."

[[dependencies.yogmod]]
modId="forge"
mandatory=true
versionRange="[40,)"
ordering="NONE"
side="BOTH"
[[dependencies.yogmod]]
modId="minecraft"
mandatory=true
versionRange="[1.18.2,)"
ordering="NONE"
side="BOTH"