modLoader="javafml"
loaderVersion="[41,)"
license="https://opensource.org/licenses/MIT"
issueTrackerURL="https://github.com/Nosiphus/yogmod/issues"
[[mods]]
modId="yogmod"
version="2023.11.05"
displayName="YogMod"
updateJSONURL=""
displayURL="https://www.nosiphus.com/"
logoFile="yogmod.png"
credits="TheVoxelBox"
authors="Nosiphus"
description="A mod that adds the VoxelBox Scientific as separate blocks."

[[dependencies.yogmod]]
modId="forge"
mandatory=true
versionRange="[41,)"
ordering="NONE"
side="BOTH"
[[dependencies.yogmod]]
modId="minecraft"
mandatory=true
versionRange="[1.19,)"
ordering="NONE"
side="BOTH"