modLoader="javafml" #mandatory

loaderVersion="[36,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.

license="https://opensource.org/licenses/MIT"

issueTrackerURL="https://github.com/Nosiphus/yogmod/issues" #optional

[[mods]] #mandatory

modId="yogmod" #mandatory

version="2022.07.02" #mandatory

displayName="YogMod" #mandatory

updateJSONURL="https://www.nosiphus.com/" #optional

displayURL="https://www.nosiphus.com/" #optional

logoFile="examplemod.png" #optional

credits="Nosiphus" #optional

authors="Nosiphus" #optional

description='''
A mod that adds the VoxelBox Scientific as separate blocks.
'''

[[dependencies.yogmod]] #optional
modId="forge" #mandatory
mandatory=true #mandatory
versionRange="[36,)" #mandatory
ordering="NONE"
side="BOTH"

[[dependencies.yogmod]]
modId="minecraft"
mandatory=true
versionRange="[1.16.5]"
ordering="NONE"
side="BOTH"