modLoader="javafml" #mandatory

loaderVersion="[32,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.

issueTrackerURL="https://github.com/Nosiphus/yogmod/issues" #optional

[[mods]] #mandatory

modId="yogmod" #mandatory

version="1.1.0-7.14.2020" #mandatory

displayName="YogMod" #mandatory

updateJSONURL="https://www.nosiphus.com/" #optional

displayURL="https://www.nosiphus.com/" #optional

logoFile="examplemod.png" #optional

credits="Nosiphus" #optional

authors="Nosiphus" #optional

description='''
YogMod
'''

[[dependencies.yogmod]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[32,)" #mandatory
    ordering="NONE"
    side="BOTH"

[[dependencies.yogmod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.1]"
    ordering="NONE"
    side="BOTH"